### ISSUE TITLE
Nueva entidad: Ciudad

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/imb.pr3.gc.2023.logistica.spring#3]
Se requiere crear una nueva entidad denominada `Ciudad` la cual debe contar con los siguientes atributos:

 - id (Integer)
 - nombre (String)
 - provinciaId (Integer) Luego se reemplazará por una relación

En el controller, se deben generar los siguientes métodos:
 
 - obtenerTodasLasCiudades (GET)
 - obtenerCiudadPorId (GET)
 - crearCiudad (POST)
 - modificarCiudad (PUT)
 - eliminarCiudad (DELETE)

**Comment by SLNacho** [comment]
#8

**Comment by SLNacho** [comment]
#8
